name: weddy
description: Weddy App

version: 0.0.1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  firebase_auth: ^0.15.4
  cached_network_image: ^2.0.0
  uuid: 2.0.4
  firebase_core: ^0.4.3+3
  firebase_storage: ^3.1.1
  # simple_animations: ^1.3.6
  sliding_up_panel: ^1.0.0
  hasura_connect: ^1.1.0
  image_picker: ^0.6.3+1
  image_downloader: ^0.19.1
  dio: ^3.0.8
  flutter_mobx: ^1.0.1
  mobx: ^1.0.0
  flutter_modular: ^0.5.1
  pin_entry_text_field: ^0.1.4
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^1.0.1
  build_runner: ^1.7.3
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/wedday-logo.png
    - assets/img/be-the-first.png  
    - assets/img/avatar.png  

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: firasans
      fonts:
        - asset: assets/fonts/firasans-Light.otf
        - asset: assets/fonts/firasans-bold.otf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

scripts:
  mobx: flutter pub run build_runner watch --delete-conflicting-outputs  